### PR TITLE
Importlib update

### PR DESCRIPTION
**Pull request by sebastian-mora**
Updated all methods using depreciated package imp to use importlib.

{Veil-Framework}/{Veil}#{ #301}

### CODE REVIEW

**Comment by sebastian-mora** [comment]
Bumping to check if there has been any updates!
Thanks

**Comment by ChrisTruncer** [comment]
I'm sorry I've completely missed this, let me get testing this. Thank you for your submission

**Comment by ChrisTruncer** [comment]
Just checked this and everything worked great, thank you for submitting this and I apologize it took me so long to review this.

Merging it in!

**Comment by sebastian-mora** [comment]
No problem thank you!

**Pull request merged**
