### PR TITLE
Improve README documentation for Py2Exe

### PR DESCRIPTION
**Pull request by xp4xbox**

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
The only thing with the provided links is they point to python2, Veil outputs python 3 code.

**Comment by xp4xbox** [comment]
The readme current says python2.7 though?

**Comment by ChrisTruncer** [comment]
Ah, then that likely needs to be updated :)

**Comment by xp4xbox** [comment]
Tested and everything works.

**Comment by ChrisTruncer** [comment]
Thanks! Merged

**Pull request merged**
