### PR TITLE
Update setup.sh

### PR DESCRIPTION
**Pull request by misuchiru03**
Fixed error checking with install on Void Linux.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Before I merge this in, since @g0tmi1k added the support, I would ideally like to have his input on this pull request.

**Comment by misuchiru03** [comment]
Right on. No worries.

**Comment by g0tmi1k** [comment]
Looks great to me!

**Comment by ChrisTruncer** [comment]
ok, then merged.

Thanks!

**Pull request merged**
