### PR TITLE
Fix wine package for Ubuntu 17+

### PR DESCRIPTION
**Pull request by leesoh**
Also removed some erroneous wine package installation from the earlier parts in the script in favour of the following Wine-specific install section.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Hi there, now that I just landed the last pull request with updates to the setup file (again :)), can you please fix any conflicts in here and then I can merge this?

Thanks!

**Comment by leesoh** [comment]
Sure thing! Will get into it tonight, hopefully.

**Comment by ChrisTruncer** [comment]
All looks good, only thing is it looks like you added the letter "t" to the beginning of the script, was that a typo?

It will likely need removed, but then this should be good to merge.

Thanks!

**Comment by leesoh** [comment]
Sorry about that!

**Comment by ChrisTruncer** [comment]
merged!

**Comment by ChrisTruncer** [comment]
thanks!

**Pull request merged**
