### PR TITLE
Add Proxy Option to payloads/cs/meterpreter/rev_https

### PR DESCRIPTION
**Pull request by martindube**
Hi!

Here is a small PR to support the detection of the default proxy. 

We also found that there was AV signature in Windows Defender on the `return "9vXU"` so I replaced it with random characters. 

Thanks,

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Hey, thanks for sending this over. I like the proxy addition, so thanks! The only thing with the return, is those four characters are used to perform a math calculation within Metasploit to make sure that it is a valid value (legitimate meterpreter callback).

I believe this can't just be any random 4 characters (but would be interested if that is not the case). Have you tested this to see if you get a valid connection after replacing those four characters?

**Comment by martindube** [comment]
Thanks for the reply!

According to a few tests, when using "ABCD", "EFGH", the 4 letter f-word
and two random four letter string, it worked well. I can do more tests and
send it in a separate PR.

**Comment by ChrisTruncer** [comment]
Since those are all working, then it sounds good. Merging this in!

**Comment by ChrisTruncer** [comment]
thanks!

**Pull request merged**
